name: Check both branches cron

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency: cron_update

jobs:
  # TODO check for EXP->EA merges and git merge headers as well
  headers:
    uses: mircearoata/satisfactory-modding-actions/.github/workflows/updateHeaders.yml@master
    with:
      branch: Experimental
    secrets:
      WWISE_URL: ${{ secrets.WWISE_URL }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  SML:
    uses: mircearoata/satisfactory-modding-actions/.github/workflows/updateSML.yml@master
    needs: [headers]
    if: always() && (needs.headers.result == 'success' || needs.headers.result == 'skipped')
    with:
      branch: Experimental
    secrets:
      WWISE_URL: ${{ secrets.WWISE_URL }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  successCheck:
    runs-on: self-hosted
    needs: [headers, SML]
    if: always() && (needs.headers.result == 'failure' || needs.SML.result == 'failure')
    steps:
      - uses: octokit/request-action@v2.x
        name: Disable cron workflow
        with:
          route: PUT /repos/{repo}/actions/workflows/{workflow_id}/disable
          repo: ${{ github.repository }}
          workflow_id: checkCron.yml # The workflow filename
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
